# Final changes in the dataset.

### Importing necessary libraries and the dataset.

In [1]:
import pandas as pd
import numpy as np

In [2]:
df_titanic = pd.read_csv("NewTitanic.tsv", sep='\t')

### I am changing the datatypes in the Age column to categorize them. Because in Orange I want to use Age info more efficiently.

In [20]:
df_titanic['Age'].unique()

array([26.  , 35.  ,  0.  , 54.  ,  2.  , 27.  , 14.  ,  4.  , 58.  ,
       20.  , 55.  , 31.  , 34.  , 15.  ,  8.  , 38.  , 19.  , 40.  ,
        0.9 , 66.  , 28.  , 42.  , 21.  , 18.  ,  3.  ,  7.  , 49.  ,
       29.  , 65.  , 28.5 ,  5.  , 11.  , 22.  , 45.  , 17.  , 32.  ,
       16.  , 25.  ,  0.83, 30.  , 33.  , 23.  , 24.  , 46.  , 59.  ,
       71.  , 37.  , 47.  , 14.5 , 70.5 , 32.5 , 12.  ,  9.  , 36.5 ,
       51.  , 55.5 , 40.5 , 44.  ,  1.  , 61.  , 56.  , 50.  , 36.  ,
       45.5 , -1.  , 20.5 , 62.  , 41.  , 52.  , 63.  , 23.5 ,  0.92,
       43.  , 60.  , 39.  , 10.  , 64.  , 13.  , 48.  ,  0.75, 53.  ,
       57.  , 80.  , 70.  , 24.5 ,  6.  ,  0.67, 30.5 ,  0.42, 34.5 ,
       74.  ,  0.7 ])

### Here, I am changing the text values to numerical ones.

In [4]:
df_titanic['Age'] = df_titanic['Age'].replace(['NoInfo', 'WrongValue'], ['0.0', '-1.0'])

In [21]:
df_titanic['Age'].unique()

array([26.  , 35.  ,  0.  , 54.  ,  2.  , 27.  , 14.  ,  4.  , 58.  ,
       20.  , 55.  , 31.  , 34.  , 15.  ,  8.  , 38.  , 19.  , 40.  ,
        0.9 , 66.  , 28.  , 42.  , 21.  , 18.  ,  3.  ,  7.  , 49.  ,
       29.  , 65.  , 28.5 ,  5.  , 11.  , 22.  , 45.  , 17.  , 32.  ,
       16.  , 25.  ,  0.83, 30.  , 33.  , 23.  , 24.  , 46.  , 59.  ,
       71.  , 37.  , 47.  , 14.5 , 70.5 , 32.5 , 12.  ,  9.  , 36.5 ,
       51.  , 55.5 , 40.5 , 44.  ,  1.  , 61.  , 56.  , 50.  , 36.  ,
       45.5 , -1.  , 20.5 , 62.  , 41.  , 52.  , 63.  , 23.5 ,  0.92,
       43.  , 60.  , 39.  , 10.  , 64.  , 13.  , 48.  ,  0.75, 53.  ,
       57.  , 80.  , 70.  , 24.5 ,  6.  ,  0.67, 30.5 ,  0.42, 34.5 ,
       74.  ,  0.7 ])

### Then changing the datatype.

In [6]:
df_titanic['Age'] = df_titanic['Age'].astype(float)

In [7]:
df_titanic['Age'].unique()

array([26.  , 35.  ,  0.  , 54.  ,  2.  , 27.  , 14.  ,  4.  , 58.  ,
       20.  , 55.  , 31.  , 34.  , 15.  ,  8.  , 38.  , 19.  , 40.  ,
        0.9 , 66.  , 28.  , 42.  , 21.  , 18.  ,  3.  ,  7.  , 49.  ,
       29.  , 65.  , 28.5 ,  5.  , 11.  , 22.  , 45.  , 17.  , 32.  ,
       16.  , 25.  ,  0.83, 30.  , 33.  , 23.  , 24.  , 46.  , 59.  ,
       71.  , 37.  , 47.  , 14.5 , 70.5 , 32.5 , 12.  ,  9.  , 36.5 ,
       51.  , 55.5 , 40.5 , 44.  ,  1.  , 61.  , 56.  , 50.  , 36.  ,
       45.5 , -1.  , 20.5 , 62.  , 41.  , 52.  , 63.  , 23.5 ,  0.92,
       43.  , 60.  , 39.  , 10.  , 64.  , 13.  , 48.  ,  0.75, 53.  ,
       57.  , 80.  , 70.  , 24.5 ,  6.  ,  0.67, 30.5 ,  0.42, 34.5 ,
       74.  ,  0.7 ])

In [8]:
df_titanic.head(5)

Unnamed: 0  PassengerId  Survived Pclass  Title  \
0           1            3         1  Third   Miss   
1           2            4         1  First    Mrs   
2           3            5         0  Third     Mr   
3           4            6         0  Third     Mr   
4           5            7         0  First     Mr   

                        FirstName   LastName     Sex   Age  SibSp  Parch  \
0                           Laina  Heikkinen  female  26.0      0      0   
1   Jacques Heath (Lily May Peel)   Futrelle  female  35.0      1      0   
2                   William Henry      Allen    male  35.0      0      0   
3                           James      Moran    male   0.0      0      0   
4                       Timothy J   McCarthy    male  54.0      0      0   

             Ticket     Fare Embarked     ship  
0  STON/O2. 3101282   7.9250        S  Titanic  
1            113803  53.1000        S  Titanic  
2            373450   8.0500        S  Titanic  
3            330877   8.4583        Q  Titanic  
4             17463  51.8625        S  Titanic

In [9]:
df_titanic.drop('Unnamed: 0', axis=1, inplace=True)

In [22]:
df_titanic.head(5)

PassengerId  Survived  Pclass  Title                       FirstName  \
0            3         1       3   Miss                           Laina   
1            4         1       1    Mrs   Jacques Heath (Lily May Peel)   
2            5         0       3     Mr                   William Henry   
3            6         0       3     Mr                           James   
4            7         0       1     Mr                       Timothy J   

    LastName     Sex   Age  SibSp  Parch            Ticket     Fare Embarked  \
0  Heikkinen  female  26.0      0      0  STON/O2. 3101282   7.9250        S   
1   Futrelle  female  35.0      1      0            113803  53.1000        S   
2      Allen    male  35.0      0      0            373450   8.0500        S   
3      Moran    male   0.0      0      0            330877   8.4583        Q   
4   McCarthy    male  54.0      0      0             17463  51.8625        S   

      ship    Ages  
0  Titanic   Adult  
1  Titanic   Adult  
2  Titanic   Adult  
3  Titanic  NoInfo  
4  Titanic   Adult

### Changing the PClass Column to int because I want to see them with numbers.

In [11]:
df_titanic['Pclass'] = df_titanic['Pclass'].replace(['First', 'Second', 'Third'], ['1', '2', '3'])

In [12]:
df_titanic['Pclass'] = df_titanic['Pclass'].astype(int)

In [13]:
df_titanic['Survived'] = df_titanic['Survived'].astype(int)

In [23]:
df_titanic['Age'].describe()

count    888.000000
mean      23.757624
std       17.610455
min       -1.000000
25%        6.000000
50%       24.000000
75%       35.000000
max       80.000000
Name: Age, dtype: float64

### Here, I am categorizing the Age column because I want to find Young examples to answer the questions. So it will be easy to see Ages categorized.

In [15]:
category = ['NoInfo', 'Child', 'Young', 'Adult', 'Senior']

df_titanic['Ages'] = pd.cut(x=df_titanic['Age'], bins=[-2,0,14,24,64,100], labels=category)

In [24]:
df_titanic.rename(columns={"Ages": "AgeCategory"})

PassengerId  Survived  Pclass  Title                       FirstName  \
0              3         1       3   Miss                           Laina   
1              4         1       1    Mrs   Jacques Heath (Lily May Peel)   
2              5         0       3     Mr                   William Henry   
3              6         0       3     Mr                           James   
4              7         0       1     Mr                       Timothy J   
..           ...       ...     ...    ...                             ...   
883          889         0       3   Miss        Catherine Helen "Carrie"   
884          890         1       1     Mr                     Karl Howell   
885          891         0       3     Mr                         Patrick   
886          892         1       1     Mr              Frederick Maxfield   
887          894         0       3   Miss           Hulda Amanda Adolfina   

      LastName     Sex   Age  SibSp  Parch            Ticket     Fare  \
0    Heikkinen  female  26.0      0      0  STON/O2. 3101282   7.9250   
1     Futrelle  female  35.0      1      0            113803  53.1000   
2        Allen    male  35.0      0      0            373450   8.0500   
3        Moran    male   0.0      0      0            330877   8.4583   
4     McCarthy    male  54.0      0      0             17463  51.8625   
..         ...     ...   ...    ...    ...               ...      ...   
883   Johnston  female   0.0      1      2        W./C. 6607  23.4500   
884       Behr    male  26.0      0      0            111369  30.0000   
885     Dooley    male  32.0      0      0            370376   7.7500   
886       Hoyt    male  38.0      1      0             19943  90.0000   
887    Vestrom  female   0.7      0      0            350406   7.8542   

    Embarked     ship AgeCategory  
0          S  Titanic       Adult  
1          S  Titanic       Adult  
2          S  Titanic       Adult  
3          Q  Titanic      NoInfo  
4          S  Titanic       Adult  
..       ...      ...         ...  
883        S  Titanic      NoInfo  
884        C  Titanic       Adult  
885        Q  Titanic       Adult  
886        S  Titanic       Adult  
887        S  Titanic       Child  

[888 rows x 15 columns]

### And finally I am changing SibSp column values to 0 or 1 instead of numbers that they have because it is easy to understand this way if they have a family with them or not.

In [17]:
df_titanic['SibSp'] = df_titanic['SibSp'].astype(bool).astype(int)

In [25]:
df_titanic['Sex'].unique()

array(['female', 'male'], dtype=object)

### Then saving the dataset to a new one.

In [19]:
df_titanic.to_csv('FinalTitanic.tsv', sep='\t')